### ISSUE TITLE
Make global scope available

### ISSUE THREAD

**Issue by Caedendi** [olegbl/d2rmm#10]
Hi,

Currently the global scope is not available in mod.js so we can't use Object,keys. I was wondering if there was some way for you to make this scope available, or explain why this is not possible. 

I have run into multiple issues where the answer seems to be "use Object.keys", which I eventually have been able to circumvent each time. This time however, I want to extend Array but this leads to circular dependencies issues. I don't really know how the global scope works and how this is related, but I'd like to use the full feature pack of javascript so I can just use the stuff people on Stack Overflow recommend.

---

**Example using extends:**
```
class AwesomeArray extends Array {
  something() {
    this.push("something");
  }
}
```
Error: _[mod] encountered a runtime error! TypeError: Class extends value undefined is not a constructor or null at 1:51_

---

**Example using prototype:**
```
Array.prototype.something = function(x) {
  this.push(x);
}
```
Error: _[mod] encountered a runtime error! TypeError: Cannot read properties of undefined (reading 'prototype') at 1:30_

---

I also want to be able to import files/classes so I can split up mod.js into parts. Is that possible?

**Comment by olegbl** [comment]
Please see the Mod API section in https://www.nexusmods.com/diablo2resurrected/mods/169:

> Note: The JavaScript inside this file is run without access to the global scope. (e.g. You’ll need to use for/in instead of Object.keys since Object is not available). The Math API is exposed for you, however.

To elaborate, this is to prevent mods from messing with other mods by overriding global scope functionality (intentionally or not).

For example, you may override the array's `filter` method on the prototype in a way that breaks another mod, and that's super hard for a user to debug because it looks like the *other* mod is broken.

There are pretty much no use cases that are blocked by this, however. For example:
```
class AwesomeArray {
  constructor(realArray) {
    this.realArray = realArray;
  }
  something() {
    this.realArray.push('something');
  }
}
const arr = [1,2,3];
const awesomeArr = new AwesomeArray(arr);
awesomeArr.something();
```

> I also want to be able to import files/classes so I can split up mod.js into parts. Is that possible?

You can certainly do that in your work environment, so long as you run some build step that packages everything up into one mod.js before giving it to D2RMM.

**Comment by olegbl** [comment]
Did some work to sandbox mods better (https://github.com/olegbl/d2rmm/commit/8d7cae8a10c743820af2eae670f8c8da8b22f816), so it will no longer require removing global scope. Version 1.5.0 will have this fixed.
