### ISSUE TITLE
D2RMM mod.js environment is too restricted (lack of file logging and require/import)

### ISSUE THREAD

**Issue by myocytebd** [olegbl/d2rmm#12]
Hi, D2RMM is great for applying existing mod, but I found it not that great to create mod.
- Lack of file logging. (for efficient debugging)
- Lack of (maybe optional) access to full node.js runtime, or at least require/import. (for efficient coding/code reuse)
----
More for logging:
D2RMM write huge log lines without cropping the file contents argument, which could make copy (export) through clipboard very slow.
e.g. `2024-02-06T15:12:56.160Z,debug,BridgeAPI.writeTsv {"filePath":<>, <full tsv contents>`

**Comment by olegbl** [comment]
I don't think I'll ever open up access to Node runtime directly - that's just asking for trouble. I'm not terribly happy with the state of the security around the sandboxing as is and wouldn't want to make it worse.

Multi-file support for mods is in the works (alongside TypeScript support): https://github.com/olegbl/d2rmm/commit/f6f77a94d2c8485246e320e1a464e03e249fc229, but due to personal reasons it will likely be a long time before I can finish and release it.

Writing logs to disk is something I've considered, but haven't had the time to do. Feel free to send a pull request, but I'm not planning to work on this any time soon myself.
