### ISSUE TITLE
Setting label disappears when value is empty

### ISSUE THREAD

**Issue by Caedendi** [olegbl/d2rmm#26]
idk if this has been fixed already but I stumbled upon this in v1.7.2.

I have the following dropdown menu setting to set a custom color for the tooltip for a certain type of item:

```
{
  "id": "TestDropdown",
  "type": "select",
  "name": "Test Setting",
  "description": "To show that labels for options with no value are broken.",
  "defaultValue": "",
  "options": [
    { "value":  "", "label": "Disable" },
    { "value": "5", "label": "Gray" },
    { "value": "6", "label": "Black" }
  ]
}
```

If "Gray" is selected, the label in the setting bar will say "Gray". If "Disable" is selected, the bar will be empty. The setting itself works though (like code/game-wise)

Can you fix this?

**Comment by olegbl** [comment]
This is an intentional feature of [MUI's `Select` component](https://mui.com/material-ui/react-select/):

> The `input` value. Providing an empty string will select no options.
> Set to an empty string `''` if you don't want any of the available options to be selected.

I could theoretically work around it by automatically replacing empty string with some dummy placeholder in every mod config that D2RMM loads, but you'd probably be better off using a real value (instead of "") anyway.

**Comment by Caedendi** [comment]
Ah that makes sense. That way you could also force a user to select an option instead of using a default value.

I'll work around it then, I'll close the issue.
