### ISSUE TITLE
Mod manager crashes the game

### ISSUE THREAD

**Issue by Marianq1** [olegbl/d2rmm#6]
Hello master!
Mod manager crashes the game. In my case it looks like my mercenary dies with 1 hit and when i want to back to town my game crashes. There was no problem till i get merc.

**Comment by olegbl** [comment]
The mod manager _cannot_ crash your game, because it does not interact with the game. D2RMM simply generates text files (.txt, .xls, .json) based on the instructions the mods provide to it.

That would be like saying that your credit card gave you food poisoning because you used it to buy a meal that didn't agree with you.
