### ISSUE TITLE
Suggestions for some new features

### ISSUE THREAD

**Issue by uuidd** [olegbl/d2rmm#7]
Suggestions for some new features
1. Automatically save game progress by date to prevent items in the storage box from disappearing after mod conflicts
2. Add - resetofflinemaps to refresh map parameters
3. Add - w - window to switch to window mode parameter

Add switch buttons for various parameters, etc

**D2RMM can also be an excellent D2R starter**

**Comment by Caedendi** [comment]
I agree D2RMM would be great as a D2R launcher/starter and support for parameters from within the GUI would be a cool addition. I always start my modded D2R using D2RMM.

**Comment by olegbl** [comment]
I'm not going to handle 1 - that should be its own tool.

I didn't want D2RMM becoming a launcher either (I only added the Run D2R button because I got very tired of telling people to go read the description for how to add "-mod D2RMM -txt"), but it seems to have already inevitably become one, so I've given up on that battle. TLDR: 2 and 3 seem reasonable to me.

Fixed in 5d746597c590f07a5224e05e055d24c75db8ea70
